device:
  device_type: cisco_ios_telnet
  host: 192.168.0.33
  port: 32771
  username: admin
  password: admin
  verbose: True
  session_log: hostname.txt

hostname: hostname

interfaces:
  - name: Loopback0
    description: Management Interface
    ip_addr: 1.1.1.1
    netmask: 255.255.255.255
  - name: GigabitEthernet0/0
    description: Uplink Interface
    ip_addr: 100.64.128.2
    netmask: 255.255.255.252
    duplex: full
    speed: 1000
    shut: false


routing:
  bgp:
    asn: 65001
    router_id: 1.1.1.1
    ecmp: 4
    networks:
      - network: 100.64.128.1
        mask: 255.255.255.255
      - network: 100.70.255.1
        mask: 255.255.255.255
    neighbors:
      - ip: 2.2.2.2
        remote_as: 65002
        description: spine_1
